datasets:
  or_bench_eval:
    hf_dataset: "bench-llms/or-bench"
    hf_config: "or-bench-80k"
    split: "train"
    limit: 150 #150
    shuffle: true
    seed: 42
  or_bench_hard:
    hf_dataset: "bench-llms/or-bench"
    hf_config: "or-bench-hard-1k"
    split: "train"
    limit: 50 #50
    shuffle: true
    seed: 42
  or_bench_toxic:
    hf_dataset: "bench-llms/or-bench"
    hf_config: "or-bench-toxic"
    split: "train"
    limit: 200 #200
    shuffle: true
    seed: 42
